a={'ID': {'type': 'integer', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'ID'}, 'TITLE': {'type': 'string', 'isRequired': True, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Название'}, 'TYPE_ID': {'type': 'crm_status', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'statusType': 'DEAL_TYPE', 'title': 'Тип'}, 'CATEGORY_ID': {'type': 'crm_category', 'isRequired': False, 'isReadOnly': False, 'isImmutable': True, 'isMultiple': False, 'isDynamic': False, 'title': 'Направление'}, 'STAGE_ID': {'type': 'crm_status', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'statusType': 'DEAL_STAGE', 'title': 'Стадия сделки'}, 'STAGE_SEMANTIC_ID': {'type': 'string', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Группа стадии'}, 'IS_NEW': {'type': 'char', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Новая сделка'}, 'IS_RECURRING': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Регулярная сделка'}, 'IS_RETURN_CUSTOMER': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Повторная сделка'}, 'IS_REPEATED_APPROACH': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Повторное обращение'}, 'PROBABILITY': {'type': 'integer', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Вероятность'}, 'CURRENCY_ID': {'type': 'crm_currency', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Валюта'}, 'OPPORTUNITY': {'type': 'double', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Сумма'}, 'IS_MANUAL_OPPORTUNITY': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'IS_MANUAL_OPPORTUNITY'}, 'TAX_VALUE': {'type': 'double', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Ставка налога'}, 'COMPANY_ID': {'type': 'crm_company', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Компания', 'settings': {'parentEntityTypeId': 4}}, 'CONTACT_ID': {'type': 'crm_contact', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'isDeprecated': True, 'title': 'Контакт'}, 'CONTACT_IDS': {'type': 'crm_contact', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': True, 'isDynamic': False, 'title': 'Контакты'}, 'QUOTE_ID': {'type': 'crm_quote', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Предложение', 'settings': {'parentEntityTypeId': 7}}, 'BEGINDATE': {'type': 'date', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дата начала'}, 'CLOSEDATE': {'type': 'date', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дата завершения'}, 'OPENED': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Доступна для всех'}, 'CLOSED': {'type': 'char', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Закрыта'}, 'COMMENTS': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Комментарий'}, 'ASSIGNED_BY_ID': {'type': 'user', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Ответственный'}, 'CREATED_BY_ID': {'type': 'user', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Кем создана'}, 'MODIFY_BY_ID': {'type': 'user', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Кем изменена'}, 'MOVED_BY_ID': {'type': 'user', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'MOVED_BY_ID'}, 'DATE_CREATE': {'type': 'datetime', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дата создания'}, 'DATE_MODIFY': {'type': 'datetime', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дата изменения'}, 'MOVED_TIME': {'type': 'datetime', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'MOVED_TIME'}, 'SOURCE_ID': {'type': 'crm_status', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'statusType': 'SOURCE', 'title': 'Источник'}, 'SOURCE_DESCRIPTION': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дополнительно об источнике'}, 'LEAD_ID': {'type': 'crm_lead', 'isRequired': False, 'isReadOnly': True, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Лид', 'settings': {'parentEntityTypeId': 1}}, 'ADDITIONAL_INFO': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Дополнительная информация'}, 'LOCATION_ID': {'type': 'location', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Местоположение'}, 'ORIGINATOR_ID': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Внешний источник'}, 'ORIGIN_ID': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Идентификатор элемента во внешнем источнике'}, 'UTM_SOURCE': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Рекламная система'}, 'UTM_MEDIUM': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Тип трафика'}, 'UTM_CAMPAIGN': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Обозначение рекламной кампании'}, 'UTM_CONTENT': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Содержание кампании'}, 'UTM_TERM': {'type': 'string', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': False, 'title': 'Условие поиска кампании'}, 'UF_CRM_PRODUCTS': {'type': 'enumeration', 'isRequired': False, 'isReadOnly': False, 'isImmutable': False, 'isMultiple': False, 'isDynamic': True, 'items': [{'ID': '45', 'VALUE': 'Элемент'}], 'title': 'UF_CRM_PRODUCTS', 'listLabel': 'UF_CRM_PRODUCTS', 'formLabel': 'UF_CRM_PRODUCTS', 'filterLabel': 'UF_CRM_PRODUCTS', 'settings': {'DISPLAY': 'LIST', 'LIST_HEIGHT': 1, 'CAPTION_NO_VALUE': '', 'SHOW_NO_VALUE': 'Y'}}}
from pprint import pprint
pprint(a)

x = {'ADDITIONAL_INFO': {'isDynamic': False,
                     'isImmutable': False,
                     'isMultiple': False,
                     'isReadOnly': False,
                     'isRequired': False,
                     'title': 'Дополнительная информация',
                     'type': 'string'},
 'ASSIGNED_BY_ID': {'isDynamic': False,
                    'isImmutable': False,
                    'isMultiple': False,
                    'isReadOnly': False,
                    'isRequired': False,
                    'title': 'Ответственный',
                    'type': 'user'},
 'BEGINDATE': {'isDynamic': False,
               'isImmutable': False,
               'isMultiple': False,
               'isReadOnly': False,
               'isRequired': False,
               'title': 'Дата начала',
               'type': 'date'},
 'CATEGORY_ID': {'isDynamic': False,
                 'isImmutable': True,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Направление',
                 'type': 'crm_category'},
 'CLOSED': {'isDynamic': False,
            'isImmutable': False,
            'isMultiple': False,
            'isReadOnly': False,
            'isRequired': False,
            'title': 'Закрыта',
            'type': 'char'},
 'CLOSEDATE': {'isDynamic': False,
               'isImmutable': False,
               'isMultiple': False,
               'isReadOnly': False,
               'isRequired': False,
               'title': 'Дата завершения',
               'type': 'date'},
 'COMMENTS': {'isDynamic': False,
              'isImmutable': False,
              'isMultiple': False,
              'isReadOnly': False,
              'isRequired': False,
              'title': 'Комментарий',
              'type': 'string'},
 'COMPANY_ID': {'isDynamic': False,
                'isImmutable': False,
                'isMultiple': False,
                'isReadOnly': False,
                'isRequired': False,
                'settings': {'parentEntityTypeId': 4},
                'title': 'Компания',
                'type': 'crm_company'},
 'CONTACT_ID': {'isDeprecated': True,
                'isDynamic': False,
                'isImmutable': False,
                'isMultiple': False,
                'isReadOnly': False,
                'isRequired': False,
                'title': 'Контакт',
                'type': 'crm_contact'},
 'CONTACT_IDS': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': True,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Контакты',
                 'type': 'crm_contact'},
 'CREATED_BY_ID': {'isDynamic': False,
                   'isImmutable': False,
                   'isMultiple': False,
                   'isReadOnly': True,
                   'isRequired': False,
                   'title': 'Кем создана',
                   'type': 'user'},
 'CURRENCY_ID': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Валюта',
                 'type': 'crm_currency'},
 'DATE_CREATE': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': True,
                 'isRequired': False,
                 'title': 'Дата создания',
                 'type': 'datetime'},
 'DATE_MODIFY': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': True,
                 'isRequired': False,
                 'title': 'Дата изменения',
                 'type': 'datetime'},
 'ID': {'isDynamic': False,
        'isImmutable': False,
        'isMultiple': False,
        'isReadOnly': True,
        'isRequired': False,
        'title': 'ID',
        'type': 'integer'},
 'IS_MANUAL_OPPORTUNITY': {'isDynamic': False,
                           'isImmutable': False,
                           'isMultiple': False,
                           'isReadOnly': False,
                           'isRequired': False,
                           'title': 'IS_MANUAL_OPPORTUNITY',
                           'type': 'char'},
 'IS_NEW': {'isDynamic': False,
            'isImmutable': False,
            'isMultiple': False,
            'isReadOnly': True,
            'isRequired': False,
            'title': 'Новая сделка',
            'type': 'char'},
 'IS_RECURRING': {'isDynamic': False,
                  'isImmutable': False,
                  'isMultiple': False,
                  'isReadOnly': False,
                  'isRequired': False,
                  'title': 'Регулярная сделка',
                  'type': 'char'},
 'IS_REPEATED_APPROACH': {'isDynamic': False,
                          'isImmutable': False,
                          'isMultiple': False,
                          'isReadOnly': False,
                          'isRequired': False,
                          'title': 'Повторное обращение',
                          'type': 'char'},
 'IS_RETURN_CUSTOMER': {'isDynamic': False,
                        'isImmutable': False,
                        'isMultiple': False,
                        'isReadOnly': False,
                        'isRequired': False,
                        'title': 'Повторная сделка',
                        'type': 'char'},
 'LEAD_ID': {'isDynamic': False,
             'isImmutable': False,
             'isMultiple': False,
             'isReadOnly': True,
             'isRequired': False,
             'settings': {'parentEntityTypeId': 1},
             'title': 'Лид',
             'type': 'crm_lead'},
 'LOCATION_ID': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Местоположение',
                 'type': 'location'},
 'MODIFY_BY_ID': {'isDynamic': False,
                  'isImmutable': False,
                  'isMultiple': False,
                  'isReadOnly': True,
                  'isRequired': False,
                  'title': 'Кем изменена',
                  'type': 'user'},
 'MOVED_BY_ID': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': True,
                 'isRequired': False,
                 'title': 'MOVED_BY_ID',
                 'type': 'user'},
 'MOVED_TIME': {'isDynamic': False,
                'isImmutable': False,
                'isMultiple': False,
                'isReadOnly': True,
                'isRequired': False,
                'title': 'MOVED_TIME',
                'type': 'datetime'},
 'OPENED': {'isDynamic': False,
            'isImmutable': False,
            'isMultiple': False,
            'isReadOnly': False,
            'isRequired': False,
            'title': 'Доступна для всех',
            'type': 'char'},
 'OPPORTUNITY': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Сумма',
                 'type': 'double'},
 'ORIGINATOR_ID': {'isDynamic': False,
                   'isImmutable': False,
                   'isMultiple': False,
                   'isReadOnly': False,
                   'isRequired': False,
                   'title': 'Внешний источник',
                   'type': 'string'},
 'ORIGIN_ID': {'isDynamic': False,
               'isImmutable': False,
               'isMultiple': False,
               'isReadOnly': False,
               'isRequired': False,
               'title': 'Идентификатор элемента во внешнем источнике',
               'type': 'string'},
 'PROBABILITY': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Вероятность',
                 'type': 'integer'},
 'QUOTE_ID': {'isDynamic': False,
              'isImmutable': False,
              'isMultiple': False,
              'isReadOnly': True,
              'isRequired': False,
              'settings': {'parentEntityTypeId': 7},
              'title': 'Предложение',
              'type': 'crm_quote'},
 'SOURCE_DESCRIPTION': {'isDynamic': False,
                        'isImmutable': False,
                        'isMultiple': False,
                        'isReadOnly': False,
                        'isRequired': False,
                        'title': 'Дополнительно об источнике',
                        'type': 'string'},
 'SOURCE_ID': {'isDynamic': False,
               'isImmutable': False,
               'isMultiple': False,
               'isReadOnly': False,
               'isRequired': False,
               'statusType': 'SOURCE',
               'title': 'Источник',
               'type': 'crm_status'},
 'STAGE_ID': {'isDynamic': False,
              'isImmutable': False,
              'isMultiple': False,
              'isReadOnly': False,
              'isRequired': False,
              'statusType': 'DEAL_STAGE',
              'title': 'Стадия сделки',
              'type': 'crm_status'},
 'STAGE_SEMANTIC_ID': {'isDynamic': False,
                       'isImmutable': False,
                       'isMultiple': False,
                       'isReadOnly': True,
                       'isRequired': False,
                       'title': 'Группа стадии',
                       'type': 'string'},
 'TAX_VALUE': {'isDynamic': False,
               'isImmutable': False,
               'isMultiple': False,
               'isReadOnly': False,
               'isRequired': False,
               'title': 'Ставка налога',
               'type': 'double'},
 'TITLE': {'isDynamic': False,
           'isImmutable': False,
           'isMultiple': False,
           'isReadOnly': False,
           'isRequired': True,
           'title': 'Название',
           'type': 'string'},
 'TYPE_ID': {'isDynamic': False,
             'isImmutable': False,
             'isMultiple': False,
             'isReadOnly': False,
             'isRequired': False,
             'statusType': 'DEAL_TYPE',
             'title': 'Тип',
             'type': 'crm_status'},
 'UF_CRM_PRODUCTS': {'filterLabel': 'UF_CRM_PRODUCTS',
                     'formLabel': 'UF_CRM_PRODUCTS',
                     'isDynamic': True,
                     'isImmutable': False,
                     'isMultiple': False,
                     'isReadOnly': False,
                     'isRequired': False,
                     'items': [{'ID': '45', 'VALUE': 'Элемент'}],
                     'listLabel': 'UF_CRM_PRODUCTS',
                     'settings': {'CAPTION_NO_VALUE': '',
                                  'DISPLAY': 'LIST',
                                  'LIST_HEIGHT': 1,
                                  'SHOW_NO_VALUE': 'Y'},
                     'title': 'UF_CRM_PRODUCTS',
                     'type': 'enumeration'},
 'UTM_CAMPAIGN': {'isDynamic': False,
                  'isImmutable': False,
                  'isMultiple': False,
                  'isReadOnly': False,
                  'isRequired': False,
                  'title': 'Обозначение рекламной кампании',
                  'type': 'string'},
 'UTM_CONTENT': {'isDynamic': False,
                 'isImmutable': False,
                 'isMultiple': False,
                 'isReadOnly': False,
                 'isRequired': False,
                 'title': 'Содержание кампании',
                 'type': 'string'},
 'UTM_MEDIUM': {'isDynamic': False,
                'isImmutable': False,
                'isMultiple': False,
                'isReadOnly': False,
                'isRequired': False,
                'title': 'Тип трафика',
                'type': 'string'},
 'UTM_SOURCE': {'isDynamic': False,
                'isImmutable': False,
                'isMultiple': False,
                'isReadOnly': False,
                'isRequired': False,
                'title': 'Рекламная система',
                'type': 'string'},
 'UTM_TERM': {'isDynamic': False,
              'isImmutable': False,
              'isMultiple': False,
              'isReadOnly': False,
              'isRequired': False,
              'title': 'Условие поиска кампании',
              'type': 'string'}}

